// Code generated by mockery v2.20.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/a-novel/auth-service/pkg/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// GetTokenStatusService is an autogenerated mock type for the GetTokenStatusService type
type GetTokenStatusService struct {
	mock.Mock
}

type GetTokenStatusService_Expecter struct {
	mock *mock.Mock
}

func (_m *GetTokenStatusService) EXPECT() *GetTokenStatusService_Expecter {
	return &GetTokenStatusService_Expecter{mock: &_m.Mock}
}

// GetTokenStatus provides a mock function with given fields: ctx, token, now
func (_m *GetTokenStatusService) GetTokenStatus(ctx context.Context, token string, now time.Time) (*models.UserTokenStatus, error) {
	ret := _m.Called(ctx, token, now)

	var r0 *models.UserTokenStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*models.UserTokenStatus, error)); ok {
		return rf(ctx, token, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *models.UserTokenStatus); ok {
		r0 = rf(ctx, token, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserTokenStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, token, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokenStatusService_GetTokenStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenStatus'
type GetTokenStatusService_GetTokenStatus_Call struct {
	*mock.Call
}

// GetTokenStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - now time.Time
func (_e *GetTokenStatusService_Expecter) GetTokenStatus(ctx interface{}, token interface{}, now interface{}) *GetTokenStatusService_GetTokenStatus_Call {
	return &GetTokenStatusService_GetTokenStatus_Call{Call: _e.mock.On("GetTokenStatus", ctx, token, now)}
}

func (_c *GetTokenStatusService_GetTokenStatus_Call) Run(run func(ctx context.Context, token string, now time.Time)) *GetTokenStatusService_GetTokenStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *GetTokenStatusService_GetTokenStatus_Call) Return(_a0 *models.UserTokenStatus, _a1 error) *GetTokenStatusService_GetTokenStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetTokenStatusService_GetTokenStatus_Call) RunAndReturn(run func(context.Context, string, time.Time) (*models.UserTokenStatus, error)) *GetTokenStatusService_GetTokenStatus_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewGetTokenStatusService interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetTokenStatusService creates a new instance of GetTokenStatusService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetTokenStatusService(t mockConstructorTestingTNewGetTokenStatusService) *GetTokenStatusService {
	mock := &GetTokenStatusService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
