// Code generated by mockery v2.33.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/a-novel/auth-service/pkg/models"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// GenerateTokenService is an autogenerated mock type for the GenerateTokenService type
type GenerateTokenService struct {
	mock.Mock
}

type GenerateTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *GenerateTokenService) EXPECT() *GenerateTokenService_Expecter {
	return &GenerateTokenService_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function with given fields: ctx, data, id, now
func (_m *GenerateTokenService) GenerateToken(ctx context.Context, data models.UserTokenPayload, id uuid.UUID, now time.Time) (*models.UserTokenStatus, error) {
	ret := _m.Called(ctx, data, id, now)

	var r0 *models.UserTokenStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserTokenPayload, uuid.UUID, time.Time) (*models.UserTokenStatus, error)); ok {
		return rf(ctx, data, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserTokenPayload, uuid.UUID, time.Time) *models.UserTokenStatus); ok {
		r0 = rf(ctx, data, id, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserTokenStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserTokenPayload, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, data, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateTokenService_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type GenerateTokenService_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - data models.UserTokenPayload
//   - id uuid.UUID
//   - now time.Time
func (_e *GenerateTokenService_Expecter) GenerateToken(ctx interface{}, data interface{}, id interface{}, now interface{}) *GenerateTokenService_GenerateToken_Call {
	return &GenerateTokenService_GenerateToken_Call{Call: _e.mock.On("GenerateToken", ctx, data, id, now)}
}

func (_c *GenerateTokenService_GenerateToken_Call) Run(run func(ctx context.Context, data models.UserTokenPayload, id uuid.UUID, now time.Time)) *GenerateTokenService_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserTokenPayload), args[2].(uuid.UUID), args[3].(time.Time))
	})
	return _c
}

func (_c *GenerateTokenService_GenerateToken_Call) Return(_a0 *models.UserTokenStatus, _a1 error) *GenerateTokenService_GenerateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GenerateTokenService_GenerateToken_Call) RunAndReturn(run func(context.Context, models.UserTokenPayload, uuid.UUID, time.Time) (*models.UserTokenStatus, error)) *GenerateTokenService_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewGenerateTokenService creates a new instance of GenerateTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenerateTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenerateTokenService {
	mock := &GenerateTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
