// Code generated by mockery v2.33.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// ValidateNewEmailService is an autogenerated mock type for the ValidateNewEmailService type
type ValidateNewEmailService struct {
	mock.Mock
}

type ValidateNewEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *ValidateNewEmailService) EXPECT() *ValidateNewEmailService_Expecter {
	return &ValidateNewEmailService_Expecter{mock: &_m.Mock}
}

// ValidateNewEmail provides a mock function with given fields: ctx, id, code, now
func (_m *ValidateNewEmailService) ValidateNewEmail(ctx context.Context, id uuid.UUID, code string, now time.Time) error {
	ret := _m.Called(ctx, id, code, now)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) error); ok {
		r0 = rf(ctx, id, code, now)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateNewEmailService_ValidateNewEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateNewEmail'
type ValidateNewEmailService_ValidateNewEmail_Call struct {
	*mock.Call
}

// ValidateNewEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - code string
//   - now time.Time
func (_e *ValidateNewEmailService_Expecter) ValidateNewEmail(ctx interface{}, id interface{}, code interface{}, now interface{}) *ValidateNewEmailService_ValidateNewEmail_Call {
	return &ValidateNewEmailService_ValidateNewEmail_Call{Call: _e.mock.On("ValidateNewEmail", ctx, id, code, now)}
}

func (_c *ValidateNewEmailService_ValidateNewEmail_Call) Run(run func(ctx context.Context, id uuid.UUID, code string, now time.Time)) *ValidateNewEmailService_ValidateNewEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *ValidateNewEmailService_ValidateNewEmail_Call) Return(_a0 error) *ValidateNewEmailService_ValidateNewEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ValidateNewEmailService_ValidateNewEmail_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, time.Time) error) *ValidateNewEmailService_ValidateNewEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewValidateNewEmailService creates a new instance of ValidateNewEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidateNewEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidateNewEmailService {
	mock := &ValidateNewEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
