// Code generated by mockery v2.33.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/a-novel/auth-service/pkg/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// GetCredentialsService is an autogenerated mock type for the GetCredentialsService type
type GetCredentialsService struct {
	mock.Mock
}

type GetCredentialsService_Expecter struct {
	mock *mock.Mock
}

func (_m *GetCredentialsService) EXPECT() *GetCredentialsService_Expecter {
	return &GetCredentialsService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, tokenRaw, now
func (_m *GetCredentialsService) Get(ctx context.Context, tokenRaw string, now time.Time) (*models.Credentials, error) {
	ret := _m.Called(ctx, tokenRaw, now)

	var r0 *models.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*models.Credentials, error)); ok {
		return rf(ctx, tokenRaw, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *models.Credentials); ok {
		r0 = rf(ctx, tokenRaw, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Credentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, tokenRaw, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCredentialsService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type GetCredentialsService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenRaw string
//   - now time.Time
func (_e *GetCredentialsService_Expecter) Get(ctx interface{}, tokenRaw interface{}, now interface{}) *GetCredentialsService_Get_Call {
	return &GetCredentialsService_Get_Call{Call: _e.mock.On("Get", ctx, tokenRaw, now)}
}

func (_c *GetCredentialsService_Get_Call) Run(run func(ctx context.Context, tokenRaw string, now time.Time)) *GetCredentialsService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *GetCredentialsService_Get_Call) Return(_a0 *models.Credentials, _a1 error) *GetCredentialsService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetCredentialsService_Get_Call) RunAndReturn(run func(context.Context, string, time.Time) (*models.Credentials, error)) *GetCredentialsService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetCredentialsService creates a new instance of GetCredentialsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetCredentialsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetCredentialsService {
	mock := &GetCredentialsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
