// Code generated by mockery v2.33.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ResendEmailValidationService is an autogenerated mock type for the ResendEmailValidationService type
type ResendEmailValidationService struct {
	mock.Mock
}

type ResendEmailValidationService_Expecter struct {
	mock *mock.Mock
}

func (_m *ResendEmailValidationService) EXPECT() *ResendEmailValidationService_Expecter {
	return &ResendEmailValidationService_Expecter{mock: &_m.Mock}
}

// ResendEmailValidation provides a mock function with given fields: ctx, tokenRaw, now
func (_m *ResendEmailValidationService) ResendEmailValidation(ctx context.Context, tokenRaw string, now time.Time) (func() error, error) {
	ret := _m.Called(ctx, tokenRaw, now)

	var r0 func() error
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (func() error, error)); ok {
		return rf(ctx, tokenRaw, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) func() error); ok {
		r0 = rf(ctx, tokenRaw, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() error)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, tokenRaw, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResendEmailValidationService_ResendEmailValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendEmailValidation'
type ResendEmailValidationService_ResendEmailValidation_Call struct {
	*mock.Call
}

// ResendEmailValidation is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenRaw string
//   - now time.Time
func (_e *ResendEmailValidationService_Expecter) ResendEmailValidation(ctx interface{}, tokenRaw interface{}, now interface{}) *ResendEmailValidationService_ResendEmailValidation_Call {
	return &ResendEmailValidationService_ResendEmailValidation_Call{Call: _e.mock.On("ResendEmailValidation", ctx, tokenRaw, now)}
}

func (_c *ResendEmailValidationService_ResendEmailValidation_Call) Run(run func(ctx context.Context, tokenRaw string, now time.Time)) *ResendEmailValidationService_ResendEmailValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *ResendEmailValidationService_ResendEmailValidation_Call) Return(_a0 func() error, _a1 error) *ResendEmailValidationService_ResendEmailValidation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResendEmailValidationService_ResendEmailValidation_Call) RunAndReturn(run func(context.Context, string, time.Time) (func() error, error)) *ResendEmailValidationService_ResendEmailValidation_Call {
	_c.Call.Return(run)
	return _c
}

// NewResendEmailValidationService creates a new instance of ResendEmailValidationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResendEmailValidationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResendEmailValidationService {
	mock := &ResendEmailValidationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
