// Code generated by mockery v2.20.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ResetPasswordService is an autogenerated mock type for the ResetPasswordService type
type ResetPasswordService struct {
	mock.Mock
}

type ResetPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *ResetPasswordService) EXPECT() *ResetPasswordService_Expecter {
	return &ResetPasswordService_Expecter{mock: &_m.Mock}
}

// ResetPassword provides a mock function with given fields: ctx, email, now
func (_m *ResetPasswordService) ResetPassword(ctx context.Context, email string, now time.Time) (func() error, error) {
	ret := _m.Called(ctx, email, now)

	var r0 func() error
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (func() error, error)); ok {
		return rf(ctx, email, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) func() error); ok {
		r0 = rf(ctx, email, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() error)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, email, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetPasswordService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type ResetPasswordService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - now time.Time
func (_e *ResetPasswordService_Expecter) ResetPassword(ctx interface{}, email interface{}, now interface{}) *ResetPasswordService_ResetPassword_Call {
	return &ResetPasswordService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, email, now)}
}

func (_c *ResetPasswordService_ResetPassword_Call) Run(run func(ctx context.Context, email string, now time.Time)) *ResetPasswordService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *ResetPasswordService_ResetPassword_Call) Return(_a0 func() error, _a1 error) *ResetPasswordService_ResetPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResetPasswordService_ResetPassword_Call) RunAndReturn(run func(context.Context, string, time.Time) (func() error, error)) *ResetPasswordService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewResetPasswordService interface {
	mock.TestingT
	Cleanup(func())
}

// NewResetPasswordService creates a new instance of ResetPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewResetPasswordService(t mockConstructorTestingTNewResetPasswordService) *ResetPasswordService {
	mock := &ResetPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
