// Code generated by mockery v2.20.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RotateSecretKeysService is an autogenerated mock type for the RotateSecretKeysService type
type RotateSecretKeysService struct {
	mock.Mock
}

type RotateSecretKeysService_Expecter struct {
	mock *mock.Mock
}

func (_m *RotateSecretKeysService) EXPECT() *RotateSecretKeysService_Expecter {
	return &RotateSecretKeysService_Expecter{mock: &_m.Mock}
}

// RotateSecretKeys provides a mock function with given fields: ctx
func (_m *RotateSecretKeysService) RotateSecretKeys(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RotateSecretKeysService_RotateSecretKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateSecretKeys'
type RotateSecretKeysService_RotateSecretKeys_Call struct {
	*mock.Call
}

// RotateSecretKeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RotateSecretKeysService_Expecter) RotateSecretKeys(ctx interface{}) *RotateSecretKeysService_RotateSecretKeys_Call {
	return &RotateSecretKeysService_RotateSecretKeys_Call{Call: _e.mock.On("RotateSecretKeys", ctx)}
}

func (_c *RotateSecretKeysService_RotateSecretKeys_Call) Run(run func(ctx context.Context)) *RotateSecretKeysService_RotateSecretKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RotateSecretKeysService_RotateSecretKeys_Call) Return(_a0 error) *RotateSecretKeysService_RotateSecretKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RotateSecretKeysService_RotateSecretKeys_Call) RunAndReturn(run func(context.Context) error) *RotateSecretKeysService_RotateSecretKeys_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRotateSecretKeysService interface {
	mock.TestingT
	Cleanup(func())
}

// NewRotateSecretKeysService creates a new instance of RotateSecretKeysService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRotateSecretKeysService(t mockConstructorTestingTNewRotateSecretKeysService) *RotateSecretKeysService {
	mock := &RotateSecretKeysService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
