// Code generated by mockery v2.20.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/a-novel/auth-service/pkg/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// UpdateProfileService is an autogenerated mock type for the UpdateProfileService type
type UpdateProfileService struct {
	mock.Mock
}

type UpdateProfileService_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateProfileService) EXPECT() *UpdateProfileService_Expecter {
	return &UpdateProfileService_Expecter{mock: &_m.Mock}
}

// UpdateProfile provides a mock function with given fields: ctx, tokenRaw, now, form
func (_m *UpdateProfileService) UpdateProfile(ctx context.Context, tokenRaw string, now time.Time, form models.UpdateProfileForm) error {
	ret := _m.Called(ctx, tokenRaw, now, form)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, models.UpdateProfileForm) error); ok {
		r0 = rf(ctx, tokenRaw, now, form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProfileService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type UpdateProfileService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenRaw string
//   - now time.Time
//   - form models.UpdateProfileForm
func (_e *UpdateProfileService_Expecter) UpdateProfile(ctx interface{}, tokenRaw interface{}, now interface{}, form interface{}) *UpdateProfileService_UpdateProfile_Call {
	return &UpdateProfileService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, tokenRaw, now, form)}
}

func (_c *UpdateProfileService_UpdateProfile_Call) Run(run func(ctx context.Context, tokenRaw string, now time.Time, form models.UpdateProfileForm)) *UpdateProfileService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(models.UpdateProfileForm))
	})
	return _c
}

func (_c *UpdateProfileService_UpdateProfile_Call) Return(_a0 error) *UpdateProfileService_UpdateProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UpdateProfileService_UpdateProfile_Call) RunAndReturn(run func(context.Context, string, time.Time, models.UpdateProfileForm) error) *UpdateProfileService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUpdateProfileService interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateProfileService creates a new instance of UpdateProfileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateProfileService(t mockConstructorTestingTNewUpdateProfileService) *UpdateProfileService {
	mock := &UpdateProfileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
