// Code generated by mockery v2.33.2. DO NOT EDIT.

package frameworkmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/a-novel/auth-service/pkg/models"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// IntrospectToken provides a mock function with given fields: ctx, token
func (_m *Client) IntrospectToken(ctx context.Context, token string) (*models.UserTokenStatus, error) {
	ret := _m.Called(ctx, token)

	var r0 *models.UserTokenStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.UserTokenStatus, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.UserTokenStatus); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserTokenStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_IntrospectToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IntrospectToken'
type Client_IntrospectToken_Call struct {
	*mock.Call
}

// IntrospectToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Client_Expecter) IntrospectToken(ctx interface{}, token interface{}) *Client_IntrospectToken_Call {
	return &Client_IntrospectToken_Call{Call: _e.mock.On("IntrospectToken", ctx, token)}
}

func (_c *Client_IntrospectToken_Call) Run(run func(ctx context.Context, token string)) *Client_IntrospectToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_IntrospectToken_Call) Return(_a0 *models.UserTokenStatus, _a1 error) *Client_IntrospectToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_IntrospectToken_Call) RunAndReturn(run func(context.Context, string) (*models.UserTokenStatus, error)) *Client_IntrospectToken_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields:
func (_m *Client) Ping() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Client_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *Client_Expecter) Ping() *Client_Ping_Call {
	return &Client_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *Client_Ping_Call) Run(run func()) *Client_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Ping_Call) Return(_a0 error) *Client_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Ping_Call) RunAndReturn(run func() error) *Client_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
